#!/usr/bin/env python3
"""Generate llms.txt, resume.json and the JSON-LD block in index.html from facts.json.
Run after editing facts.json:  python3 build.py
"""
import json, re, pathlib

root = pathlib.Path(__file__).parent
f = json.loads((root / "facts.json").read_text())

# llms.txt
lines = [f"# {f['name']}, qriousguy.com", f"> {f['positioning']} {f['summary']}", "",
         f"Updated {f['updated']}. {f['availability']}", "", "## Facts (dated, public)"]
for x in f["figures"]:
    lines.append(f"- {x['value']} {x['what']} (source: {x['source']}; confirmed {x['confirmed']})")
lines += ["", "## Experience"]
for w in f["work"]:
    span = f"{w['startDate']} to {w.get('endDate', 'present')}"
    lines.append(f"- {w['position']}, {w['name']}, {span}" + (f". {w['summary']}" if w.get("summary") else ""))
    for h in w.get("highlights", []):
        lines.append(f"  - {h}")
for e in f["education"]:
    lines.append(f"- {e['institution']}, {e['endDate']}")
lines += ["", "## Recognition"] + [f"- {a}" for a in f["awards"]]
lines += ["", "## Projects"]
for p in f["projects"]:
    lines.append(f"- {p['name']} ({p['status']}" + (f", {p['url']}" if p.get("url") else "") + f"): {p['description']}")
lines += ["", "## Writing"] + [f"- {p['title']} ({p['date']}): {p['url']}" for p in f["posts"]]
lines += ["", "## Contact", f"- Email: {f['email']}"] + [f"- {p['network']}: {p['url']}" for p in f["profiles"]]
lines += ["", "## Machine-readable", "- https://qriousguy.com/resume.json (JSON Resume schema)", "- https://qriousguy.com/feed.xml (RSS)", ""]
(root / "llms.txt").write_text("\n".join(lines))

# resume.json (JSON Resume schema)
resume = {
    "$schema": "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json",
    "basics": {"name": f["name"], "label": f"{f['title']}, applied AI", "email": f["email"], "url": f["url"],
               "summary": f"{f['positioning']} {f['summary']} {f['availability']}",
               "location": f["location"], "profiles": f["profiles"]},
    "work": [{k: v for k, v in w.items()} for w in f["work"]],
    "education": f["education"],
    "awards": [{"title": a} for a in f["awards"]],
    "projects": f["projects"],
    "publications": [{"name": p["title"], "releaseDate": p["date"], "url": p["url"], "summary": p["dek"]} for p in f["posts"]],
    "skills": [{"name": k} for k in f["knowsAbout"]],
    "meta": {"lastModified": f["updated"], "canonical": f["url"] + "/resume.json"},
}
(root / "resume.json").write_text(json.dumps(resume, indent=2, ensure_ascii=False) + "\n")

# JSON-LD in index.html
ld = {
    "@context": "https://schema.org", "@type": "Person", "name": f["name"], "jobTitle": f["title"],
    "description": f["summary"], "url": f["url"] + "/", "email": "mailto:" + f["email"],
    "worksFor": {"@type": "Organization", "name": "Hakimo.ai", "url": "https://hakimo.ai"},
    "address": {"@type": "PostalAddress", "addressLocality": f["location"]["city"], "addressCountry": f["location"]["countryCode"]},
    "sameAs": [p["url"] for p in f["profiles"]], "knowsAbout": f["knowsAbout"],
}
idx = root / "index.html"
html = idx.read_text()
block = ('<!-- ld+json:start (generated by build.py from facts.json; do not edit by hand) -->\n  <script type="application/ld+json">\n'
         + json.dumps(ld, indent=2, ensure_ascii=False) + '\n  </script>\n  <!-- ld+json:end -->')
html, n = re.subn(r"<!-- ld\+json:start.*?<!-- ld\+json:end -->", lambda m: block, html, flags=re.S)
assert n == 1, "ld+json markers not found in index.html"
idx.write_text(html)
print("wrote llms.txt, resume.json, index.html JSON-LD")
